spring:
  datasource:
    url: jdbc:mysql://34.64.156.85/DCI_database
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: DCI
    password: dci
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        query.in_clause_parameter_padding: true
  logging:
    level:
      org.hibernate.type.descriptor.sql.BasicBinder: trace
  web:
    resources:
      static-locations: classpath:/static/
server:
  port: 8080